# Project
project_name: face_mosaic
exp_name: 'mask_rcnn'

# Model
backbone: 'mask_rcnn_R_101_FPN_3x'
batch: 8
lr: 0.0025
iter: 10000



# Path (Change to your own paths!)
path:
  train: 'yai/Face_Mosaic/data/widerface/WIDER_train/images'
  val: 'yai/Face_Mosaic/data/widerface/WIDER_val/images'
  test: 'yai/Face_Mosaic/data/widerface/WIDER_test/images'
  annot: 'yai/Face_Mosaic/data/widerface/wider_face_split'
  output_root: 'ckpts'
  load_ckpt: ~
  
# Logger
wandb:
  use_wandb: False
  
